name = "TheForgedLand"
author = "Alice C."
version = "2.0.1"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b1798bc5004d1e291bbde9b6dfcd3e3d69d4d7ad61240aef90cba84210873a3"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
