name = "TheForgedLand"
author = "Alice C."
version = "2.0.0"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d5f4361679bb8c277f45fbb2f276c8e8555ed23f66ba77f511aeeebc77c7614"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
