name = "TheForgedLand"
author = "Alice C."
version = "2.0.1"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52d06ffe2ce8a202d2a889a4cecb8e709e1e5f20ef390f8c97ad8a90019a67b4"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
