name = "TheForgedLand"
author = "Alice C."
version = "2.0.0"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0da217658c727f1546f6c8e29d4b632e28bc2ab5c97186092f2d4d2636087db"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
