name = "TFL"
author = "Alice C"
version = "1.2.1"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "903a225dd49ac7d336058e8f4c3f121b66c5b68f66f2e0f6f3b1ed4d4a3dcaab"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
unsup = "0.2.0"
