name = "TheForgedLand"
author = "Alice C."
version = "2.0.1"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c801fa4b723ba49e8cb8da6c1a0e709786e321da3978fd947ff785be0b188601"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
