name = "TheForgedLand"
author = "Alice C."
version = "2.1.2"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "990dd8bf346fdf9222a77011d90c2ba0c90bea7413e45328e723ad91543ca9a5"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
unsup = "0.2.0"
