name = "TFL"
author = "Alice C"
version = "1.2.2"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac21d37f2d40f51a279a3e330cee80c662556b9d52444d7339dc1790885161e1"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
unsup = "0.2.0"
