name = "TheForgedLand"
author = "Alice C."
version = "2.0.0"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8eb3339c0b3bc5860741e36dca83a5e662c17acbab8e5eeef4f17e9658399ff"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
