name = "TheForgedLand"
author = "Alice C."
version = "2.0.0"
description = "A special modpack made for TheForgedLand SMP 2nd Season"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36021511f42fc09177ca71f4488288f074ff1a102d0d9f7c0c6b7909cd3f2b73"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
unsup = "0.2.0"
