name = "TFL"
author = "Alice C"
version = "1.2.1"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "851b19200256e7404f1970b02f689f541e94e1dcdf5de391977c7a4e0449d328"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
unsup = "0.2.0"
