name = "TFL"
author = "Alice C"
version = "1.2.1"
description = "A special modpack made for TheForgedLand SMP"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca6d0a8e9146dfa8eb1397ad1626da9cde0b983957d0d36e741d4a8c85d03fb"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
unsup = "0.2.0"
