[flavor_groups.ui-aesthetics]
name = "UI Aesthetics"
description = "The legendary tooltips mod is a simple aesthetic mod that makes tooltips of special items stand out more"
side = "client"
choices = ["ui-aesthetics_on", "ui-aesthetics_off"]

[flavor_groups.rei]
name = "REI"
description = "Roughly Enough items (and its addons) will be Essential on your journey through Create and Farmer's Delight, allowing you to search for recipes of any item within the modpack!"
side = "both"
choices = ["rei_on","rei_off"]

[flavor_groups.ipn]
name = "IPN Sorter"
description = "with Inventory profiles Next, you will be able to quickly sort your inventory with a click of a button! not only that, but there are plenty of other features available in its configs if you are willing to try them out"
side = "client"
choices = ["ipn_on", "ipn_off"]

[flavor_groups.sodium]
name = "Sodium"
description = "Sodium is a free and open-source rendering engine replacement for the Minecraft client which greatly improves frame rates and stuttering while fixing many graphical issues. It boasts wide compatibility with the Fabric mod ecosystem when compared to other mods, and it does so without compromising on how the game looks, giving you that authentic block game feel"
side = "client"
choices = ["sodium_on", "sodium_off"]



[metafile.legendary-tooltips]
flavors = "ui-aesthetics_on"
[metafile.prism-lib]
flavors = "ui-aesthetics_on"
[metafile.advancement-plaques]
flavors = "ui-aesthetics_on"
[metafile.iceberg]
flavors = "ui-aesthetics_on"

[metafile.roughly-enough-items]
flavors = "rei_on"
[metafile.roughly-enough-loot-tables]
flavors = "rei_on"
[metafile.roughly-enough-professions-rep]
flavors = "rei_on"
[metafile.roughly-enough-resources]
flavors = "rei_on"
[metafile.roughly-enough-trades]
flavors = "rei_on"

[metafile.inventory-profiles-next]
flavors = "ipn_on"
[metafile.libipn]
flavors = "ipn_on"

[metafile.fabric-language-kotlin]
flavors = ["rei_on","ipn_on"]

[metafile.sodium]
flavors = "sodium_on"
[metafile.sodium-extra]
flavors = "sodium_on"
[metafile.reeses-sodium-options]
flavors = "sodium_on"
[metafile.indium]
flavors = "sodium_on"
