[flavor_groups.base]
name = "Base Mods"
side = "both"
choices = [ "base_on", "base_off",]
description = "these mods are essential for you to even be able to join the server. only remove them if you know what you are doing!"

[flavor_groups.minimap]
name = "Journeymap!"
side = "client"
choices = [ "minimap_on", "minimap_off",]
description = "With Journeymap, you will be able to better navigate through your journeys, besides also having both a minimap and a worldmap for you to use, being able to mark points of interest in the map by creating waypoints there!"

[flavor_groups.ui-aesthetics]
name = "UI Aesthetics"
side = "client"
choices = [ "ui-aesthetics_on", "ui-aesthetics_off",]
description = "These aesthetic mods will add small aesthetic tweaks to your game\nMods list:\n<ul></ul>\n"

[flavor_groups.ui-tools]
name = "Interface-tools"
side = "client"
choices = [ "ui-tools_on", "ui-tools_off",]
description = "with This assortment of tools, you will be able to quickly sort your inventory with a click of a button and easily check recipes to explore Create and Farmers's Delight!\namongst those tools, you will find:\n<ul></ul>\n"

[flavor_groups.performance]
name = "performance"
side = "both"
choices = [ "performance_on", "performance_off",]
description = "mods:\n<ul></ul>\n"

[flavor_groups.extra]
name = "Extra!"
side = "client"
choices = [ "extra_on", "extra_off",]
description = "mods:\n<ul></ul>\n"

[flavor_groups.immersion]
name = "Immersion!"
side = "client"
choices = [ "immersion_on", "immersion_off",]
description = "mods:\n<ul></ul>\n"

[flavor_groups.misc]
name = "Miscelaneus"
description = "Miscelaneus mods that do not quite fit a propper group"
side = "client"
choices = [ "misc_on", "misc_off",]

[flavor_groups.bug-fixes]
name = "Bugfixes!"
side = "both"
choices = [ "bug-fixes_on", "bug-fixes_off",]
description = "mods:\n<ul></ul>\n"

[flavor_groups.debug]
name = "Debug Toolkit"
side = "both"
choices = [ "debug_on", "debug_off",]
description = "mods:\n<ul>\n</ul>\n"

[metafile.additional-structures-fabric]
flavors = "misc_on"

[metafile.advancement-plaques-fabric]
flavors = "misc_on"

[metafile.amecs]
flavors = "misc_on"

[metafile.another-furniture]
flavors = "misc_on"

[metafile.appleskin]
flavors = "misc_on"

[metafile.architects-palette-fabric]
flavors = "misc_on"

[metafile.architectury-api]
flavors = "misc_on"

[metafile.backpacked-fabric]
flavors = "misc_on"

[metafile.better-potion-visuals]
flavors = "misc_on"

[metafile.camera-utils]
flavors = "misc_on"

[metafile.charmonium]
flavors = "misc_on"

[metafile.chimes]
flavors = "misc_on"

[metafile.chipped]
flavors = "misc_on"

[metafile.cleancut]
flavors = "misc_on"

[metafile.cloth-config]
flavors = "misc_on"

[metafile.clumps]
flavors = "misc_on"

[metafile.colorful-enchantments]
flavors = "misc_on"

[metafile.configured-fabric]
flavors = "misc_on"

[metafile.connectivity]
flavors = "misc_on"

[metafile.corgilib]
flavors = "misc_on"

[metafile.create-deco-fabric]
flavors = "misc_on"

[metafile.create-fabric]
flavors = "misc_on"

[metafile.create-steam-n-rails]
flavors = "misc_on"

[metafile.creativecore]
flavors = "misc_on"

[metafile.cull-less-leaves]
flavors = "misc_on"

[metafile.cultural-delights-fabric]
flavors = "misc_on"

[metafile.decorative-blocks]
flavors = "misc_on"

[metafile.delightful-creators-fabric]
flavors = "misc_on"

[metafile.ecologics]
flavors = "misc_on"

[metafile.effective]
flavors = "misc_on"

[metafile.entityculling]
flavors = "misc_on"

[metafile.expanded-delight]
flavors = "misc_on"

[metafile.explorify]
flavors = "misc_on"

[metafile.extra-alchemy]
flavors = "misc_on"

[metafile.fabric-api]
flavors = "misc_on"

[metafile.fabric-language-kotlin]
flavors = "misc_on"

[metafile.falling-leaves-fabric]
flavors = "misc_on"

[metafile.farmers-delight-fabric]
flavors = "misc_on"

[metafile.ferritecore-fabric]
flavors = "misc_on"

[metafile.findme]
flavors = "misc_on"

[metafile.framework-fabric]
flavors = "misc_on"

[metafile.free-cam]
flavors = "misc_on"

[metafile.geckolib]
flavors = "misc_on"

[metafile.immersive-structures]
flavors = "misc_on"

[metafile.immersive-structures-ii-nether-edition]
flavors = "misc_on"

[metafile.indium]
flavors = "misc_on"

[metafile.inventory-profiles-next]
flavors = "misc_on"

[metafile.itemphysic-lite]
flavors = "misc_on"

[metafile.itemswapper]
flavors = "misc_on"

[metafile.kitsune]
flavors = "misc_on"

[metafile.kubejs]
flavors = "misc_on"

[metafile.kubejs-create]
flavors = "misc_on"

[metafile.lambdabettergrass]
flavors = "misc_on"

[metafile.lambdynamiclights]
flavors = "misc_on"

[metafile.lazydfu]
flavors = "misc_on"

[metafile.leaves-slabs]
flavors = "misc_on"

[metafile.leaves-us-in-peace]
flavors = "misc_on"

[metafile.legendary-tooltips-fabric]
flavors = "misc_on"

[metafile.libipn]
flavors = "misc_on"

[metafile.light-overlay]
flavors = "misc_on"

[metafile.lithium]
flavors = "misc_on"

[metafile.log-begone]
flavors = "misc_on"

[metafile.memoryleakfix]
flavors = "misc_on"

[metafile.microdurability]
flavors = "misc_on"

[metafile.missing-wilds]
flavors = "misc_on"

[metafile.mixintrace]
flavors = "misc_on"

[metafile.modmenu]
flavors = "misc_on"

[metafile.natures-compass]
flavors = "misc_on"

[metafile.netherportalfix]
flavors = "misc_on"

[metafile.nethers-delight-fabric]
flavors = "misc_on"

[metafile.oh-the-biomes-youll-go-fabric]
flavors = "misc_on"

[metafile.openblocks-elevator-fabric]
flavors = "misc_on"

[metafile.origins]
flavors = "misc_on"

[metafile.origins-classes]
flavors = "misc_on"

[metafile.origins-plus-plus]
flavors = "misc_on"

[metafile.origins-umbrellas]
flavors = "misc_on"

[metafile.owo-lib]
flavors = "misc_on"

[metafile.pehkui]
flavors = "misc_on"

[metafile.reacharound]
flavors = "misc_on"

[metafile.reeses-sodium-options]
flavors = "misc_on"

[metafile.resourceful-lib]
flavors = "misc_on"

[metafile.rhino]
flavors = "misc_on"

[metafile.roughly-enough-items]
flavors = "misc_on"

[metafile.roughly-enough-loot-tables]
flavors = "misc_on"

[metafile.roughly-enough-professions-rep]
flavors = "misc_on"

[metafile.roughly-enough-resources]
flavors = "misc_on"

[metafile.roughly-enough-trades]
flavors = "misc_on"

[metafile.satin-api]
flavors = "misc_on"

[metafile.simple-voice-chat]
flavors = "misc_on"

[metafile.slice-and-dice]
flavors = "misc_on"

[metafile.smooth-boot]
flavors = "misc_on"

[metafile.sodium]
flavors = "misc_on"

[metafile.sodium-extra]
flavors = "misc_on"

[metafile.sodium-shadowy-path-blocks]
flavors = "misc_on"

[metafile.spark]
flavors = "misc_on"

[metafile.starlight]
flavors = "misc_on"

[metafile.status-effect-bars]
flavors = "misc_on"

[metafile.terrablender-fabric]
flavors = "misc_on"

[metafile.the-twilight-forest]
flavors = "misc_on"

[metafile.tooltipfix]
flavors = "misc_on"

[metafile.towns-and-towers]
flavors = "misc_on"

[metafile.trinkets]
flavors = "misc_on"

[metafile.twilight-origins]
flavors = "misc_on"

[metafile.visuality]
flavors = "misc_on"

[metafile.why-does-my-glass-sound-like-that]
flavors = "misc_on"

[metafile.xaeros-minimap]
flavors = "misc_on"

[metafile.xaeros-world-map]
flavors = "misc_on"

[metafile.xl-packets-fabric]
flavors = "misc_on"

[metafile.yacl]
flavors = "misc_on"

[metafile.youre-in-grave-danger]
flavors = "misc_on"
