[flavor_groups.minimap]
name = "Minimap mods:"
[[flavor_groups.minimap.choices]]
id = "xaero"
name = "Xaero's Minimaps"
description = """
Xaero's minimap & World map will make quick work of your travel and avoid you from getting lost around!
"""
[[flavor_groups.minimap.choices]]
id = "journey"
name = "Journeymap!"
description = """With Journeymap, you will be able to better navigate through your journeys, besides also having both a minimap and a worldmap for you to use.
"""

[flavor_groups.ui-aesthetics]
name = "UI Aesthetics"
description = """
These aesthetic mods will add small aesthetic tweaks to your game
Mods list:
<ul>\
	<li>legendary-tooltips</li>\
	<li>advancement-plaques</li>\
	<li>better-enchanted-books</li>\
	<li>dynamiccrosshair</li>\
	<li>dynamiccrosshaircompat</li>\
	<li>iceberg</li>\
	<li>microdurability</li>\
	<li>prism-lib</li>\
	<li>status-effect-bars</li>\
</ul>
"""
side = "client"
choices = [ "ui-aesthetics_on", "ui-aesthetics_off",]


[flavor_groups.ui-tools]
name = "Interface-tools"
description = """
with This assortment of tools, you will be able to quickly \
sort your inventory with a click of a button and easily check \
recipes to explore Create and Farmers's Delight!
amongst those tools, you will find:
<ul>\
	<li>Roughly enough items (and addons)</li>\
	<li>Appleskin (food info)</li>\
	<li>Inventory Profiles Next (item sorter)</li>\
	<li>Amecs</li>\
</ul>
"""
side = "client"
choices = [ "ui-tools_on", "ui-tools_off",]


[flavor_groups.performance]
name = "performance"
description = """
mods:
<ul>\
	<li>clumps</li>\
	<li>entityculling</li>\
	<li>ferrite-core</li>\
	<li>forgetmechunk</li>\
	<li>indium</li>\
	<li>lazydfu</li>\
	<li>lithium</li>\
	<li>moreculling</li>\
	<li>morecullingextra</li>\
	<li>reeses-sodium-options</li>\
	<li>smoothboot-fabric</li>\
	<li>sodium-extra</li>\
	<li>sodium</li>\
	<li>starlight</li>\
</ul>
"""
side = "both"
choices = [ "performance_on", "performance_off",]


[flavor_groups.extra]
name = "Extra!"
description = """
mods:
<ul>\
	<li>chatcalc</li>\
	<li>clickthrough</li>\
	<li>freecam</li>\
	<li>hotbarcycle</li>\
	<li>iceberg</li>\
	<li>invmove</li>\
	<li>itemswapper</li>\
	<li>reacharound</li>\
	<li>show-me-your-skin</li>\
	<li>stepup</li>\
	<li>xaeros-world-map</li>\
</ul>
"""
side = "client"
choices = [ "extra_on", "extra_off",]


[flavor_groups.immersion]
name = "Immersion!"
description = """
mods:
<ul>\
	<li>bedrockwaters</li>\
	<li>charmonium</li>\
	<li>interactic</li>\
	<li>lambdabettergrass</li>\
	<li>lambdynamiclights</li>\
	<li>moreculling</li>\
	<li>morecullingextra</li>\
	<li>visuality</li>\
	<li>wdmgslt</li>\
</ul>
"""
side = "client"
choices = [ "immersion_on", "immersion_off",]

[flavor_groups.misc]
name = "Miscelaneus"
description = "Miscelaneus mods that do not quite fit a propper group"
side = "client"
choices = ["misc_on", "misc_off"]

[flavor_groups.bug-fixes]
name = "Bugfixes!"
description = """
mods:
<ul>\
	<li>advancements-debug</li>\
	<li>block_limit_fix</li>\
	<li>gotta-go-fast-fabric</li>\
	<li>libre-exp-fix</li>\
	<li>memoryleakfix</li>\
	<li>timeoutout</li>\
	<li>tooltipfix</li>\
	<li>view-distance-fix</li>\
</ul>
"""
side = "both"
choices = [ "bug-fixes_on", "bug-fixes_off",]

[flavor_groups.debug]
name = "Debug Toolkit"
description = """
mods:
<ul>\
	<li>mixintrace</li>\
	<li>spark</li>\
</ul>
"""
side = "both"
choices = [ "debug_on", "debug_off"]
