[flavor_groups.base]
name = "Base Mods"
side = "both"
choices = ["base_on","base_off]
description = """
"""

[flavor_groups.minimap]
name = "Minimap mods:"
[[flavor_groups.minimap.choices]]
id = "xaero"
name = "Xaero's Minimaps"
description = """
Xaero's minimap & World map will make quick work of your travel and avoid you from getting lost around!
"""
[[flavor_groups.minimap.choices]]
id = "journey"
name = "Journeymap!"
description = """With Journeymap, you will be able to better navigate through your journeys, besides also having both a minimap and a worldmap for you to use.
"""

[flavor_groups.ui-aesthetics]
name = "UI Aesthetics"
side = "client"
choices = [ "ui-aesthetics_on", "ui-aesthetics_off",]
description = """
These aesthetic mods will add small aesthetic tweaks to your game
Mods list:
<ul>\
</ul>
"""


[flavor_groups.ui-tools]
name = "Interface-tools"
side = "client"
choices = [ "ui-tools_on", "ui-tools_off",]
description = """
with This assortment of tools, you will be able to quickly \
sort your inventory with a click of a button and easily check \
recipes to explore Create and Farmers's Delight!
amongst those tools, you will find:
<ul>\
</ul>
"""


[flavor_groups.performance]
name = "performance"
side = "both"
choices = [ "performance_on", "performance_off",]
description = """
mods:
<ul>\
</ul>
"""


[flavor_groups.extra]
name = "Extra!"
side = "client"
choices = [ "extra_on", "extra_off",]
description = """
mods:
<ul>\
</ul>
"""


[flavor_groups.immersion]
name = "Immersion!"
side = "client"
choices = [ "immersion_on", "immersion_off",]
description = """
mods:
<ul>\
</ul>
"""

[flavor_groups.misc]
name = "Miscelaneus"
description = "Miscelaneus mods that do not quite fit a propper group"
side = "client"
choices = ["misc_on", "misc_off"]

[flavor_groups.bug-fixes]
name = "Bugfixes!"
side = "both"
choices = [ "bug-fixes_on", "bug-fixes_off",]
description = """
mods:
<ul>\
</ul>
"""

[flavor_groups.debug]
name = "Debug Toolkit"
side = "both"
choices = [ "debug_on", "debug_off"]
description = """
mods:
<ul>
</ul>
"""
